Repository JinWorkBench/even-flix, pull requests merged in 2025-01, with the labels that each got.

#3 모달 팝업 추가
  src/App.tsx
  src/components/DetailModal/components/ModalHeader.tsx
  src/components/DetailModal/components/ModalPoster.tsx
  src/components/DetailModal/components/ModalPosterButtons.tsx
  src/components/DetailModal/page.tsx
  src/hooks/useOnclickOutside.ts
Labels: 🌟 feat

#5 모달 상단 영화 정보 섹션 추가
  src/components/DetailModal/components/ModalInfoSummary.tsx
  src/components/DetailModal/page.tsx
Labels: 🎨 UI

#4 환경변수 예시 파일 생성
  .env.example
Labels: 🌟 feat

#6 Components 추가 - Card, Poster(Top10Card), CardList, PosterList
  public/index.html
  src/components/Card.tsx
  src/components/CardList.tsx
  src/components/Poster.tsx
  src/components/PosterList.tsx
  src/data/__dummyMoviesAndSeries.ts
  src/index.css
  src/pages/__cardComponentTest.tsx
  src/styles/swiper.css
Labels: 🌟 feat, 🎨 UI

#8 상단 네비게이션 바와 하단 푸터 1차 PR
  src/components/Footer.tsx
  src/components/NavBar.tsx
  src/components/NavItem.tsx
Labels: 🌟 feat, 🎨 UI

#10 시즌 에피소드 UI 및 기능 추가
  public/json/season.json
  src/components/DetailModal/Model/Episodes.ts
  src/components/DetailModal/components/ModalDropdown.tsx
  src/components/DetailModal/components/ModalEpisode.tsx
  src/components/DetailModal/components/ModalEpisodes.tsx
  src/components/DetailModal/components/ModalInfoSummary.tsx
  src/components/DetailModal/page.tsx
Labels: 🌟 feat, 🎨 UI

#13 라우팅 라이브러리 추가 및 홈화면 UI
  package-lock.json
  package.json
  src/App.tsx
  src/api/requests.tsx
  src/index.tsx
  src/pages/HomePage/page.tsx
Labels: 🌟 feat, 🎨 UI

#12 상단 네비게이션 바 검색 창 조건과 디자인, 프로필 메뉴 디자인 수정
  src/components/NavBar.tsx
Labels: 🐛 bug, 🎨 UI

#11 함께시청된콘텐츠 추가
  public/json/recommdation.json
  src/components/DetailModal/Model/Recommend.ts
  src/components/DetailModal/components/ModalEpisode.tsx
  src/components/DetailModal/components/ModalEpisodes.tsx
  src/components/DetailModal/components/ModalInfoSummary.tsx
  src/components/DetailModal/components/ModalRecommend.tsx
  src/components/DetailModal/components/ModalRecommends.tsx
  src/components/DetailModal/page.tsx
  src/util/calculate.ts
Labels: 🎨 UI

#14 Banner css 수정한 부분 먼저 올리겠습니다!
  src/api/requests.ts
  src/components/Banner.tsx
  src/pages/HomePage/page.tsx
Labels: 🎨 UI

#15 홈페이지 섹션 추가 구현
  src/api/requests.ts
  src/components/CardList.tsx
  src/components/PosterList.tsx
  src/pages/HomePage/page.tsx
Labels: 🐛 bug, 🎨 UI

#16 상세화면 모달에서 라우터로 변경, 모델 위치 및 이름 변경
  src/App.tsx
  src/components/DetailModal/components/ModalDropdown.tsx
  src/components/DetailModal/components/ModalEpisode.tsx
  src/components/DetailModal/components/ModalEpisodes.tsx
  src/components/DetailModal/components/ModalHeader.tsx
  src/components/DetailModal/components/ModalInfoDetail.tsx
  src/components/DetailModal/components/ModalInfoSummary.tsx
  src/components/DetailModal/components/ModalPoster.tsx
  src/components/DetailModal/components/ModalRecommend.tsx
  src/components/DetailModal/components/ModalRecommends.tsx
  src/components/DetailModal/page.tsx
  src/models/ Media.ts
  src/models/Credit.ts
  src/models/Episodes.ts
  src/models/Keyword.ts
  src/models/Recommend.ts
Labels: 🌟 feat

#17 Media.ts 앞 공백 제거
  src/App.tsx
  src/components/DetailModal/components/ModalDropdown.tsx
  src/components/DetailModal/components/ModalEpisodes.tsx
  src/components/DetailModal/components/ModalInfoDetail.tsx
  src/components/DetailModal/components/ModalInfoSummary.tsx
  src/components/DetailModal/components/ModalPoster.tsx
  src/components/DetailModal/page.tsx
  src/models/Media.ts
Labels: 🐛 bug

#18 컴포넌트 및 홈 화면 데이터 모델명 변경
  src/components/Card.tsx
  src/components/CardList.tsx
  src/components/Poster.tsx
  src/components/PosterList.tsx
  src/data/__dummyMoviesAndSeries.ts
  src/models/Media.ts
  src/pages/HomePage/page.tsx
  src/pages/__cardComponentTest.tsx
Labels: ♻️ refactor

#19 모달화면 API 연결
  src/App.tsx
  src/components/Card.tsx
  src/components/DetailModal/components/ModalEpisodes.tsx
  src/components/DetailModal/components/ModalInfoDetail.tsx
  src/components/DetailModal/components/ModalInfoSummary.tsx
  src/components/DetailModal/components/ModalRecommends.tsx
  src/components/DetailModal/page.tsx
  src/models/Keyword.ts
  src/util/calculate.ts
Labels: 🌟 feat

#22 더미 디테일 카드 추가로 기능 구현
  src/components/Card.tsx
  src/components/CardList.tsx
  src/components/Poster.tsx
  src/components/PosterList.tsx
  src/components/__DummyDetailCard.tsx
  src/pages/HomePage/page.tsx
  src/styles/swiper.css
Labels: 🌟 feat

#24 Profile 생성 및 1차 구현 (Profile.tsx 위치 components->pages로 수정)
  src/pages/Profile/page.tsx
Labels: 🎨 UI

#26 카드 그리드 컴포넌트 추가 및 내가 찜한 리스트 페이지 구현
  src/App.tsx
  src/components/CardGrid.tsx
  src/components/CardList.tsx
  src/components/PosterList.tsx
  src/components/__DummyDetailCard.tsx
  src/context/FavoriteContext.tsx
  src/pages/HomePage/page.tsx
  src/pages/MyList/page.tsx
Labels: 🌟 feat, 🎨 UI

#25 영화페이지에 들어 갈 배너 입니다.
  src/App.tsx
  src/api/requests.ts
  src/components/MovieBanner.tsx
  src/pages/MoviePage/page.tsx
  src/pages/__pages__
Labels: 🎨 UI

#21 검색페이지 구현
  public/json/credit.json
  public/json/keywords.json
  public/json/movie.json
  public/json/recommdation.json
  public/json/season.json
  public/json/series.json
  src/App.tsx
  src/components/Card.tsx
  src/components/NavBar.tsx
  src/components/__DummyDetailCard.tsx
  src/components/__components__
  src/hooks/__hooks__
  src/hooks/useDebounce.ts
  src/models/Media.ts
  src/pages/HomePage/page.tsx
  src/pages/SearchPage/page.tsx
Labels: 🌟 feat

#27 서브 헤더바 제작과 언어별로 찾아보기 페이지 생성 및 연동
  src/App.tsx
  src/components/NavBar.tsx
  src/components/SubHeader.tsx
  src/pages/OriginalAudio/page.tsx
Labels: 🌟 feat, 🎨 UI

#28 상세화면 뒷편 배경 나오지않던 이슈 수정
  src/App.tsx
  src/components/Detail/ModalDropdown.tsx
  src/components/Detail/ModalEpisode.tsx
  src/components/Detail/ModalEpisodes.tsx
  src/components/Detail/ModalHeader.tsx
  src/components/Detail/ModalInfoDetail.tsx
  src/components/Detail/ModalInfoSummary.tsx
  src/components/Detail/ModalPoster.tsx
  src/components/Detail/ModalPosterButtons.tsx
  src/components/Detail/ModalRecommend.tsx
  src/components/Detail/ModalRecommends.tsx
  src/components/__DummyDetailCard.tsx
  src/pages/DetailPage/page.tsx
Labels: 🐛 bug

#30 리팩토링: 컴포넌트 데이터 모델 수정 + 그에 따른 페이지 코드 수정
  src/App.tsx
  src/components/Card.tsx
  src/components/CardGrid.tsx
  src/components/CardList.tsx
  src/components/Poster.tsx
  src/components/PosterList.tsx
  src/components/__DummyDetailCard.tsx
  src/context/FavoriteContext.tsx
  src/models/Media.ts
  src/pages/HomePage/page.tsx
  src/pages/MoviePage/page.tsx
  src/pages/MyList/page.tsx
  src/pages/SearchPage/page.tsx
Labels: 🎨 UI, ♻️ refactor

#29 요즘 대세 컨텐츠 페이지 구현 및 소소한 버그 수정
  src/App.tsx
  src/api/axios.ts
  src/components/Card.tsx
  src/components/Detail/ModalPosterButtons.tsx
  src/components/Detail/ModalRecommend.tsx
  src/components/Footer.tsx
  src/components/NavBar.tsx
  src/components/Poster.tsx
  src/components/__DummyDetailCard.tsx
  src/models/Media.ts
  src/pages/DetailPage/page.tsx
  src/pages/NewContentsPage/page.tsx
Labels: 🌟 feat

#31 디테일 카드 ui 작업 완료
  src/components/Card.tsx
  src/components/CardGrid.tsx
  src/components/CardList.tsx
  src/components/DetailCard.tsx
  src/components/PosterList.tsx
  src/components/__DummyDetailCard.tsx
  src/models/Media.ts
Labels: 🌟 feat, 🎨 UI

#33 언어별로 찾아보기 페이지 CardGrid 연결
  src/components/NavBar.tsx
  src/components/SubHeader.tsx
  src/pages/OriginalAudio/page.tsx
Labels: 🐛 bug, 🎨 UI

#34 Profile과 홈화면 연결
  src/App.tsx
  src/components/NavBar.tsx
  src/pages/Profile/page.tsx
Labels: 🎨 UI

#35 상단 네비게이션 바 자잘한 버그 수정
  src/components/NavBar.tsx
Labels: 🐛 bug

#37 카드 컴포넌트들 버그 수정 및 디테일 추가
  src/components/CardList.tsx
  src/components/DetailCard.tsx
  src/components/PosterList.tsx
  src/components/Tooltip.tsx
  src/styles/Tooltip.css
Labels: 🐛 bug, 🎨 UI

#38 언어별로 찾아보기 페이지 Media 매핑과 정렬 기준 구현
  src/components/SubHeader.tsx
  src/pages/OriginalAudio/page.tsx
Labels: 🌟 feat, ♻️ refactor

#39 모달에서 뒤로가기 되지 않는 이슈 수정
  src/components/DetailCard.tsx
Labels: 🐛 bug
